<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Route Demo</title>
</head>
<body>
<table width="900px">
	<tr bgcolor="yellow"><td colspan=3 width="900px">Route Demo</td></tr>
	<tr>
		<td width="200px">
			<a href="http://routedemo/">HOME</a></li>
			<h4>Uses conventional approach to params</h4>
			<ul>
				<li><a href="/ops/calc/add/op1/3/op2/3">add 3 + 3</a></li>
				<li><a href="/ops/calc/sub/op1/22/op2/18">sub 22 - 18</a></li>
				<li><a href="/ops/calc/div/op1/18/op2/6">div 18 / 6</a></li>
				<li><a href="/ops/calc/div/op1/5/op2/0">div 5 / 0</a></li>
				<li><a href="/ops/calc/mul/op1/3/op2/3">multiply 3 * 3</a></li>
			<h4>Uses application.ini routing</h4>
			<ul>
				<li><a href="/calc/3/4">calc 3 + 4</a></li>
			</ul>
			<h4>Uses bootstrap routing</h4>
			<ul>
				<li><a href="/add/3/3">add 3 + 3</a></li>
				<li><a href="/sub/22/18">sub 22 - 18</a></li>
				<li><a href="/div/18/6">div 18 / 6</a></li>
				<li><a href="/div/5/0">div 5 / 0</a></li>
				<li><a href="/mul/3/3">multiply 3 * 3</a></li>
			</ul>
		</td>
		<td width="50px">&nbsp;</td>
		<td width="650px">
			<?php echo $this->layout()->content; ?>
		</td>
	</tr>
</table>
</body>
</html>
