<table cellpadding=0 cellspacing=0>
<tr><td valign=top>
<?php echo $this->header; ?>
<div style='border:1px;width:500px;height:240px;background-color:#FFFF99;font: 12pt helvetica,sans;'>
<?php echo $this->name; ?>
</div>
<div style='border:1px;width:500px;height:200px;background-color:#FFFF66;font: 12pt helvetica,sans;'>
<?php echo $this->remainder; ?>
</div>
</td>
<td valign=top>
</div>
<div style='border:1px;width:500px;height:440px;background-color:#FFFF33;font: 12pt helvetica,sans;'>
<?php echo $this->address; ?>
</div>
<?php echo $this->end; ?>
</td></tr>
</table>
<p><?php echo $this->msg; ?></p>