<div style="width:250px; height:300; float: left;">
<img src="/images/old_teletype.png" width="250" height="247" />
</div>
<div style="width:150px; height:300; float: left;">
<h3>Source Code on github.com</h3>
<ul>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net" target="_blank">This Website</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/AuthDemo" target="_blank">Auth Demo</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/FormDemo" target="_blank">Form Demo</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/PluginDemo" target="_blank">Plugin Demo</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/NavDemo" target="_blank">Nav Demo</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/RouteDemo" target="_blank">Route Demo</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/JqueryDemo" target="_blank">Jquery Demo</a></li>
<li><a href="https://github.com/dbierer/zf.unlikelysource.net/tree/master/demos/HelperDemo" target="_blank">Helper Demo</a></li>
</ul>
</div>
<div style="width:400px;float: left;">
<h3>Nico Edtinger's Zend_Pdf_Page Implementation</h3>
<p>One of the main drawbacks to Zend_Pdf is that when you use Zend_Pdf_Page::drawText() to put a
line of text onto your PDF file, you can only place one line at a time.</p>
<p>Nico has proposed (a proprosal not adopted) a method "drawTextBlock()" which places a <i>block</i>
of text on the screen.  His algorithm takes into account font width and height.  Click on the link
below to view his solution.</p>
<ul>
<li><a href="/index/code/nico/1">Nico</a></li>
</ul>
<?php if ($this->nico) : ?>
	<pre>
	<?php echo $this->nico; ?>
	</pre>
<?php endif; ?>
</div>
