<h1>Overview</h1>
<img src="/images/old_vlf_antenna.jpg" width="250" height="188" style="float: left; margin: 10px;" />
<p>
This website is devoted to Zend Framework 1.x.  
Zend Framework is a rapid application develpment environment written entirely in PHP. 
The framework consists of a series of classes which can be used in isolation or as part of an
application entirely written using ZF.  
<p>
There are a number of demos which you can explore by clicking on an item in the top menu.
In addition you can view the code and access the sister websites of unlikelysource.net and unlikelysource.com.
</p>
<p>
<h3>Other Stuff</h3> 
<ul>
<li>registered members can also download the code.  To register, <a href="http://zf2.unlikelysource.org/user/register">click here</a></li>
<li>For more information on Zend Framework 1.x <a href="http://framework.zend.com/">click here</a></li>
<li>To obtain the latest Beta and for more info on ZF2 <a href="http://packages.zendframework.com/">click here</a></li>
</ul>
