<?php 
$locale 			= Zend_Registry::get('Zend_Locale');
$session 			= new Zend_Session_Namespace('calendar');
$showDate['year'] 	= date('Y');
$showDate['month']	= date('m');
$showDate['day']	= date('d');
$showDate['week']	= date('W');
$year				= ($session->year)  ? $session->year  : date('Y');
$month				= ($session->month) ? $session->month : date('m');
$week				= ($session->week)  ? $session->week  : date('W');
$prevWeek			= $week - 1;
$prevMonth			= $month;
$prevYear			= $year;
$nextWeek			= $week + 1;
$nextMonth			= $month;
$nextYear			= $year;
if ($prevWeek < 1) {
	//
}
if ($prevMonth < 1) {
	$prevMonth = 12;
	$prevYear--;
}
if ($nextMonth > 12) {
	$nextMonth = 1;
	$nextYear++;
}
?>
<style>
.calendar_month_class {
	border: 1px;
	margin: 5px;
}
.calendar_week_class {
	
}
.calendar_day_class {
	text-align: center;
	border: thin solid white;
	width: 50px;
	height: 50px;
}
.calendar_day_header_class {
	text-align: center;
	border: 0px;
	width: 50px;
	height: 10px;
	color: #8888FF;
}
.calendar_selected_day_class {
	text-align: center;
	border: thin solid yellow;
	width: 50px;
	height: 50px;
	color: yellow;
}
</style>
<h3><a href="/calendar/view/month/m/<?php echo $prevMonth; ?>/y/<?php echo $prevYear; ?>">-</a>
	&nbsp;&nbsp;
	Week <?php echo $week; ?>
	&nbsp;&nbsp;
	<?php echo $locale->getTranslation($month, 'month') . '&nbsp;&nbsp;&nbsp;' . $year; ?>
	&nbsp;&nbsp;
	<a href="/calendar/view/month/m/<?php echo $nextMonth; ?>/y/<?php echo $nextYear; ?>">+</a>
</h3>
<?php echo $this->bigMonth($locale, $month, $year, $showDate); ?>
