This module demonstrates one possible use for Zend_Queue.  When you "visit" the chat room, the RoomController 
retrieves messages currently on the queue and displays them.  If you wish to post a message, select "POST MESSAGE", 
enter a username and message, and then click "Post".  The message will be placed on the queue for all to view.
<p><?php echo $this->notify; ?></p>
<p><?php echo $this->messagesForm; ?></p>