<?php
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>JQuery Demo</title>
<!-- Set up JQuery -->
<?php $this->headLink()
           ->prependStylesheet('/css/global.css')
           ->appendStylesheet('/css/sunny/jquery-ui-1.8.5.custom.css');?>
<?php echo $this->headLink() ?>   
<!-- HIGHLY IMPORTANT: jquery ui version MUST be 1.8.5 or above!!! -->             
<?php echo $this->jQuery()
				->setUiVersion('1.8.5')
				->setVersion('1.4.2'); ?>
</head>
<body>
<table bgcolor="#ECE972">
<tr><td colspan=2 bgcolor="#F5F259"><h1 style="font: bold 16pt helvetica;">JQuery Demo</h1></td></tr>
<tr>
<td bgcolor="#F8F67B" width=25% valign="top">
<ul>
<li><a href="/index/index">Home</a></li>
<li><a href="/index/test1">AjaxLink Function</a></li>
<li><a href="/index/actest-no-ajax">Autocomplete No AJAX</a></li>
<li><a href="/index/actest">Autocomplete With AJAX</a></li>
<li><a href="/index/all-products">All Products</a></li>
</ul>
</td>
<td bgcolor="#E3F5A6" width=75%><?php echo $this->layout()->content; ?></td>
</tr>
</table>
</body>
</html>
